### ISSUE TITLE
Task: Pull Food Information from API for Food Page

### ISSUE THREAD

**Issue by ajconnol** [cse442-fall-2019-offering/442projects-sonic#30]
Pull nutrition information from given food from API to generate Food page.

**Comment by lwu8891** [comment]
Task Test:

1) Data API pull/page generation

      Step 1) Go to application home page 
 
     Step 2) Type a food into Search bar

     Step 3) Select any option

     Step 4) Allow page to load

     Expected Results: Nutrition information corresponding to the selected food is visible and 
     formatted to corresponding labels. Nutrition information is accurate to the food product selected.
