### ISSUE TITLE
User Story: Logging in  

### ISSUE THREAD

**Issue by shawnmam** [cse442-fall-2019-offering/442projects-sonic#4]
As a business person, I have a few phones, and I would like to be able to log in and out from different devices using my email and password. It should check if my username and password is correct and if is then and only then let me log in. Then on any device I use, my information should carry over.

**Comment by ajconnol** [comment]
Acceptance Tests:

1) Type valid username and password in fields and press login:
      welcomed and taken to their homepage

2) Type invalid username and password combination and press login
       given an error message saying username and password combination isn't valid
