### ISSUE TITLE
User Story: Manual Food Item Search

### ISSUE THREAD

**Issue by lwu8891** [cse442-fall-2019-offering/442projects-sonic#42]
As a dieter, I want to search for foods, so I can view their nutrition information.

**Comment by lwu8891** [comment]
Acceptance Tests:

1) When I type in the search bar, relevant results appear as I type.

2) Clicking on a result brings me to a page for the corresponding food.

**Comment by ajconnol** [comment]
Task 1:  Add Search Bar to Homepage 

Task Tests 

1) Search bar is visible

Step 1) Load home page

Expected Result: Search Bar is visible 
2) Search bar is usable and accepts text

Step 1) Load home page 

Step 2) Click search bar

Step 3) Type 'apple'

Expected Results: word apple appears in search bar

-------------------------------------------------------------------





Task 2:  Link search results to Food Page

Task test

Step 1) Go to app home screen

Step 2) type in any food

Step 3) click on a result

Expected Result: Page for food that was selected loads








-----------------------------------------------------

Task 3: Pull foods for live search

Task test:

1) Live Results

  Step 1) Go to application home page

  Step 2) Press Search bar

  Step 3) Type "apple" 

  Expected Results: Search results related to "apple" populate under the search bar.
