### ISSUE TITLE
User Story: View Nutritional Information

### ISSUE THREAD

**Issue by lwu8891** [cse442-fall-2019-offering/442projects-sonic#43]
As a dieter, I want to see nutritional information about a food so that I can make informed decisions about what I eat.

**Comment by lwu8891** [comment]
Acceptance Test:

1) If I go to a food page, I should be able to see the nutrition contents of that food.

**Comment by ajconnol** [comment]
Task 1) Pull food from API for food page 

Task Test:

1) Data API pull/page generation

  Step 1) Go to application home page 

 Step 2) Type a food into Search bar

 Step 3) Select any option

 Step 4) Allow page to load

 Expected Results: Nutrition information corresponding to the selected food is visible and 
 formatted to corresponding labels. Nutrition information is accurate to the food product
