### ISSUE TITLE
User Story: Changing Max Nutrient

### ISSUE THREAD

**Issue by shawnmam** [cse442-fall-2019-offering/442projects-sonic#7]
As a dieter, I want to set/change my maximum allowance of a nutrient, so that I may adjust my diet to my needs.

**Comment by ajconnol** [comment]
Acceptance Tests:   

1) Attempt to Submit 10 servings of mac and cheese when user is at max calories. 
    Pushes warning, showing how many calories over the limit the food would take them, 
    ask if they wish to continue with Yes or no buttons.

1a) Click yes 
      Calories are added to daily calorie counter

1a) Click no
     Window closes, user is back and food item page
